name: Generate zip for release

on:
  release:
    types:
    - published
    branches:
    - main

jobs:
  createZip:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2.3.4
      with:
        ref: main
    - name: Zip files
      working-directory: './OriginRealms-x-Presence-Footsteps'
      run: 'zip -r Presence-Footsteps-x-OriginRealms-${{ github.event.release.tag_name }}.zip assets/ pack.mcmeta pack.png'
    - name: Upload zip to release
      uses: AButler/upload-release-assets@v2.0
      with:
        files: 'OriginRealms-x-Presence-Footsteps/Presence-Footsteps-x-OriginRealms-${{ github.event.release.tag_name }}.zip'
        repo-token: '${{ secrets.GITHUB_TOKEN }}'
    