name: Generate zip for release

on:
  workflow_dispatch:
    inputs:
      version:
        description: The Release version
        required: true
        type: string
      title:
        description: The Title to use for the release
        required: true
        type: string

jobs:
  createZip:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2.3.4
      with:
        ref: main
    - name: Zip files
      working-directory: './OriginRealms-x-Presence-Footsteps'
      run: 'zip -r Presence-Footsteps-x-OriginRealms-${{ inputs.version }}.zip assets/ pack.mcmeta pack.png'
    - name: Create release and upload
      uses: Kir-Antipov/mc-publish@v3.2
      with:
        files-primary: 'OriginRealms-x-Presence-Footsteps/Presence-Footsteps-x-OriginRealms-${{ inputs.version }}.zip'
        
        name: ${{ inputs.title }}
        version: ${{ inputs.version }}
        version-type: release
        changelog-file: '.github/changelogs/${{ inputs.version }}.md'
        game-versions: |
          1.19.4
        
        modrinth-id: xYfiwE5K
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
        modrinth-featured: false
        dependencies: |
          rcTfTZr3 | depends
        
        github-token: ${{ secrets.GITHUB_TOKEN }}
        github-tag: ${{ inputs.version }}
        github-commitish: main
    
